### ISSUE TITLE
How do you generate the Second Parent

### ISSUE THREAD

**Issue by ahx-code** [guisehn/genetic-magic-square-finder#14]
Thanks for explaining the first parent generation  ([5, 0, 5, 4, 3, 1, 2, 1, 0])

How do you calculate the second parent? [1, 6, 6, 0, 0, 0, 0, 1, 0]

Thanks

**Comment by ahx-code** [comment]
Could it be [4 1 5 6 9 8 7 2 3] ?

or 

4 1 5
6 9 8
7 2 3

**Comment by guisehn** [comment]
@AhmetTavli 

> How do you calculate the second parent? [1, 6, 6, 0, 0, 0, 0, 1, 0]
> Thanks for explaining the first parent generation ([5, 0, 5, 4, 3, 1, 2, 1, 0])
> How do you calculate the second parent? [1, 6, 6, 0, 0, 0, 0, 1, 0]

If you're talking about the example on README.md, these two are actually the children, not the parents: `[5, 0, 5, 4, 3, 1, 2, 1, 0]` and `[1, 6, 6, 0, 0, 0, 0, 1, 0]`

They are calculated by doing a simple single-point crossover over the two parents with a random point selection. In that example, the parents are `[5, 0, 5, 4, 3, 1, 0, 1, 0]` and `[1, 6, 6, 0, 0, 0, 2, 1, 0]` ([found by tournament selection](https://github.com/guisehn/genetic-magic-square-finder#selection-for-crossover)).

The crossover point randomly generated was 5, so the first child is going to have the first six elements of the first parent (elements from index `0` to `5`) and the rest of the second parent, while the second child is going to have the first six of the second parent, and the rest of the first parent. To make it clearer:

```
parent1 = [5, 0, 5, 4, 3, 1, x, x, x]
parent2 = [x, x, x, x, x, x, 2, 1, 0]
first_child = [5, 0, 5, 4, 3, 1, 2, 1, 0]

parent1 = [x, x, x, x, x, x, 0, 1, 0]
parent2 = [1, 6, 6, 0, 0, 0, x, x, x]
second_child = [1, 6, 6, 0, 0, 0, 0, 1, 0]
```

**Comment by guisehn** [comment]
@AhmetTavli 

> How do you calculate the second parent? [1, 6, 6, 0, 0, 0, 0, 1, 0]
> Thanks for explaining the first parent generation ([5, 0, 5, 4, 3, 1, 2, 1, 0])
> How do you calculate the second parent? [1, 6, 6, 0, 0, 0, 0, 1, 0]

If you're talking about the example on README.md, these two are actually the children, not the parents: `[5, 0, 5, 4, 3, 1, 2, 1, 0]` and `[1, 6, 6, 0, 0, 0, 0, 1, 0]`. The two parents are `[5, 0, 5, 4, 3, 1, 0, 1, 0]` and `[1, 6, 6, 0, 0, 0, 2, 1, 0]`

The children are calculated by doing a simple single-point crossover over the two parents with a random point selection. In that example, the parents are `[5, 0, 5, 4, 3, 1, 0, 1, 0]` and `[1, 6, 6, 0, 0, 0, 2, 1, 0]` ([found by tournament selection](https://github.com/guisehn/genetic-magic-square-finder#selection-for-crossover)).

The crossover point randomly generated was 5, so the first child is going to have the first six elements of the first parent (elements from index `0` to `5`) and the rest of the second parent, while the second child is going to have the first six of the second parent, and the rest of the first parent. To make it clearer:

```
parent1 = [5, 0, 5, 4, 3, 1, x, x, x]
parent2 = [x, x, x, x, x, x, 2, 1, 0]
first_child = [5, 0, 5, 4, 3, 1, 2, 1, 0]

parent1 = [x, x, x, x, x, x, 0, 1, 0]
parent2 = [1, 6, 6, 0, 0, 0, x, x, x]
second_child = [1, 6, 6, 0, 0, 0, 0, 1, 0]
```

Hope this helps!

**Comment by guisehn** [comment]
@AhmetTavli 

> How do you calculate the second parent? [1, 6, 6, 0, 0, 0, 0, 1, 0]
> Thanks for explaining the first parent generation ([5, 0, 5, 4, 3, 1, 2, 1, 0])
> How do you calculate the second parent? [1, 6, 6, 0, 0, 0, 0, 1, 0]

If you're talking about the example on README.md, these two you've mentioned are actually the children, not the parents: `[5, 0, 5, 4, 3, 1, 2, 1, 0]` and `[1, 6, 6, 0, 0, 0, 0, 1, 0]`. The two parents are `[5, 0, 5, 4, 3, 1, 0, 1, 0]` and `[1, 6, 6, 0, 0, 0, 2, 1, 0]`

The children are calculated by doing a simple single-point crossover over the two parents with a random point selection. In that example, the parents are `[5, 0, 5, 4, 3, 1, 0, 1, 0]` and `[1, 6, 6, 0, 0, 0, 2, 1, 0]` ([found by tournament selection](https://github.com/guisehn/genetic-magic-square-finder#selection-for-crossover)).

The crossover point randomly generated was 5, so the first child is going to have the first six elements of the first parent (elements from index `0` to `5`) and the rest of the second parent, while the second child is going to have the first six of the second parent, and the rest of the first parent. To make it clearer:

```
parent1 = [5, 0, 5, 4, 3, 1, x, x, x]
parent2 = [x, x, x, x, x, x, 2, 1, 0]
first_child = [5, 0, 5, 4, 3, 1, 2, 1, 0]

parent1 = [x, x, x, x, x, x, 0, 1, 0]
parent2 = [1, 6, 6, 0, 0, 0, x, x, x]
second_child = [1, 6, 6, 0, 0, 0, 0, 1, 0]
```

Hope this helps!

**Comment by guisehn** [comment]
@AhmetTavli 

> How do you calculate the second parent? [1, 6, 6, 0, 0, 0, 0, 1, 0]
> Thanks for explaining the first parent generation ([5, 0, 5, 4, 3, 1, 2, 1, 0])
> How do you calculate the second parent? [1, 6, 6, 0, 0, 0, 0, 1, 0]

If you're talking about the example on README.md, these two you've mentioned are actually the children, not the parents: `[5, 0, 5, 4, 3, 1, 2, 1, 0]` and `[1, 6, 6, 0, 0, 0, 0, 1, 0]` are the two children. The two parents that generated these children are `[5, 0, 5, 4, 3, 1, 0, 1, 0]` and `[1, 6, 6, 0, 0, 0, 2, 1, 0]`.

The children are calculated by doing a simple single-point crossover over the two parents with a random point selection. In that example, the parents are `[5, 0, 5, 4, 3, 1, 0, 1, 0]` and `[1, 6, 6, 0, 0, 0, 2, 1, 0]` ([found by tournament selection](https://github.com/guisehn/genetic-magic-square-finder#selection-for-crossover)).

The crossover point randomly generated was 5, so the first child is going to have the first six elements of the first parent (elements from index `0` to `5`) and the rest of the second parent, while the second child is going to have the first six of the second parent, and the rest of the first parent. To make it clearer:

```
parent1 = [5, 0, 5, 4, 3, 1, x, x, x]
parent2 = [x, x, x, x, x, x, 2, 1, 0]
first_child = [5, 0, 5, 4, 3, 1, 2, 1, 0]

parent1 = [x, x, x, x, x, x, 0, 1, 0]
parent2 = [1, 6, 6, 0, 0, 0, x, x, x]
second_child = [1, 6, 6, 0, 0, 0, 0, 1, 0]
```

Hope this helps!

**Comment by guisehn** [comment]
Closing this issue. If you have any additional question, please open another one.
